import * as THREE from 'three'
import type { PointerState } from '../types'
import type { StoryPhase } from '../director/StoryDirector'
const COLORS:Record<StoryPhase,string>={intro:'#eef1f4',pullIn:'#66788f',tunnel:'#273b67',forum:'#416d82',video:'#b8663c',live:'#8f286e',search:'#222a3a',ai:'#e8f0ff',return:'#eef1f4'}
export class EraSpace{
 readonly group=new THREE.Group(); private backdrop:THREE.Mesh; private floor:THREE.Mesh; private screen:THREE.Mesh; private ring:THREE.Mesh; private tunnel=new THREE.Group(); private exhibit=new THREE.Group(); private motes:THREE.Points; private phase:StoryPhase='intro'; private fromColor=new THREE.Color(COLORS.intro); private toColor=new THREE.Color(COLORS.intro); private transition=1
 constructor(){
  this.backdrop=new THREE.Mesh(new THREE.PlaneGeometry(30,18),new THREE.MeshBasicMaterial({color:COLORS.intro,fog:true}));this.backdrop.position.set(0,5.5,-7);this.group.add(this.backdrop)
  this.floor=new THREE.Mesh(new THREE.BoxGeometry(30,.22,26),new THREE.MeshBasicMaterial({color:'#d9dee4',fog:true}));this.floor.position.y=-.12;this.group.add(this.floor)
  const plinth=new THREE.Mesh(new THREE.CylinderGeometry(1.35,1.55,.55,8),new THREE.MeshBasicMaterial({color:'#fff',transparent:true,opacity:.92}));plinth.position.y=.28;this.group.add(plinth)
  this.screen=new THREE.Mesh(new THREE.BoxGeometry(3.8,2.25,.18),new THREE.MeshBasicMaterial({color:'#0b101b',fog:true}));this.screen.position.set(0,2.8,-5.8);this.group.add(this.screen)
  const glass=new THREE.Mesh(new THREE.CylinderGeometry(1.05,1.05,1.7,32,1,true),new THREE.MeshBasicMaterial({color:'#b8d7e8',transparent:true,opacity:.16,side:THREE.DoubleSide}));glass.position.y=1.25;this.group.add(glass)
  this.ring=new THREE.Mesh(new THREE.TorusGeometry(2.1,.12,8,32),new THREE.MeshBasicMaterial({color:'#8de4ff',transparent:true,opacity:.9}));this.ring.position.set(0,3,-4.8);this.tunnel.add(this.ring);for(let i=1;i<7;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(1.4+i*.65,.06,8,32),new THREE.MeshBasicMaterial({color:i%2?'#8de4ff':'#ff8bd8',transparent:true,opacity:.5}));r.position.z=-4.8-i*.65;this.tunnel.add(r)}this.group.add(this.tunnel);this.group.add(this.exhibit)
  const pos=new Float32Array(720);for(let i=0;i<240;i++){pos[i*3]=(Math.random()-.5)*22;pos[i*3+1]=Math.random()*10;pos[i*3+2]=-Math.random()*8}const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(pos,3));this.motes=new THREE.Points(geo,new THREE.PointsMaterial({color:'#a8dfff',size:.07,transparent:true,opacity:.55}));this.group.add(this.motes);this.setPhase('intro')
 }
 private add(x:number,y:number,z:number,w:number,h:number,d:number,c:string){const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshBasicMaterial({color:c,fog:true}));m.position.set(x,y,z);this.exhibit.add(m)}
 private rebuild(p:StoryPhase){this.exhibit.clear();if(p==='forum')for(let i=-2;i<=2;i++)for(let j=0;j<3;j++)this.add(i*1.7,1+j*1.05,-4-j*.5,1.35,.72,.25,'#79c4d4');if(p==='video'){this.add(0,.08,-3.2,10,.08,.35,'#f5c26b');for(let i=-4;i<=4;i++)this.add(i*1.1,.18,-3.2,.7,.24,.5,'#ff8d55')}if(p==='live')for(let i=-2;i<=2;i++)this.add(i*1.7,2.1,-4.6,1.05,2.3,.18,'#ff4fb2');if(p==='search')for(let i=-3;i<=3;i++)this.add(i*1.4,1.4+Math.abs(i)*.22,-4.4,1.05,2.8+Math.abs(i)*.4,.18,'#8996ad');if(p==='ai')for(let i=0;i<7;i++)this.add((i-3)*1.55,1.6+Math.sin(i)*.35,-4-Math.abs(i-3)*.25,1.5,2.1,.06,'#fff')}
 setPhase(p:StoryPhase){if(p===this.phase&&this.transition>=1)return;this.fromColor.copy((this.backdrop.material as THREE.MeshBasicMaterial).color);this.toColor.set(COLORS[p]);this.phase=p;this.transition=0;this.ring.visible=true;this.screen.visible=true;this.rebuild(p)}
 update(dt:number,time:number,pointer:PointerState){this.transition=Math.min(1,this.transition+dt/1.8);const e=this.transition<.5?this.transition*2:1;const pull=Math.sin(this.transition*Math.PI);(this.backdrop.material as THREE.MeshBasicMaterial).color.copy(this.fromColor).lerp(this.toColor,e);(this.floor.material as THREE.MeshBasicMaterial).color.lerp(new THREE.Color(this.phase==='intro'||this.phase==='return'?'#d9dee4':'#202735'),e);this.tunnel.visible=this.phase==='pullIn'||this.phase==='tunnel'||pull>.02;this.tunnel.rotation.z+=dt*(1+pull*10);this.tunnel.position.x+=(pointer.world.x*.18*pull-this.tunnel.position.x)*Math.min(1,dt*5);this.tunnel.position.y+=(pointer.world.y*.08*pull-this.tunnel.position.y)*Math.min(1,dt*5);this.ring.scale.setScalar(1+Math.sin(time*2)*.08+pointer.energy*.35+pull*1.2);this.motes.rotation.y+=dt*(.04+pull*.5);this.screen.visible=this.phase==='intro'||this.phase==='pullIn'||this.phase==='return'||pull>.02;this.screen.scale.set(1+pull*1.4,1-pull*.25,1);this.exhibit.scale.setScalar(.72+.28*e);this.exhibit.rotation.y=pull*.35;this.group.scale.setScalar(1+pull*.06)}
 dispose(){this.group.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Points){o.geometry.dispose();const m=o.material;Array.isArray(m)?m.forEach(x=>x.dispose()):m.dispose()}})}
}
